### PR TITLE
feat: card component added

### PR DESCRIPTION
**Pull request by humzahasan**
- Added variation of horizontally and vertically stacked card components

### CODE REVIEW

**Review by sanu29 — APPROVED** [review]
Great work. Could not find any changes to be done except a comment. File structure is good. Naming convention has consistency and class names are meaning full. Code is clean and readable. 

Good for me 👍

**Comment by itsmebipul00** [comment]
Great Work!! Small thing: card-badge-content is not laid out properly

**Comment by humzahasan** [comment]
> Great Work!! Small thing: card-badge-content is not laid out properly

Can you explain this please, as in the name can be changed or you are talking about the strcutre/content ?

**Comment by itsmebipul00** [comment]
As I can see your card-badge-content is absolute wrt card-badge,  which is why it is overflowing a bit from the card image. Instead what you could do is wrap card-badge-content inside card-media and make it absolute wrt it, after that apply appropriate top, left, bottom, right. 
OR you could just give some top like 10px to card-badge-content to see the changes

**Pull request merged**
